### PR TITLE
Update voice status using "Channel Workers"

### PR DESCRIPTION
**Pull request by auyer**
## Change Proposal

This PR changes the way the Voice States are updated.

### Why?

The current procedure is slow.

I invite you to test this for yourself, but I understand this is hard to measure. I've spent a few hours testing with a 10 players party (they were very patient).

### How it is done in this proposal :

A number of "workers" is started, each one in a different goroutine.
When users are popped from the priority list, they are sent into a Channel, and the workers do the updating concurrently.
Once the channel is closed, and empty, the workers are dropped from existence.

### CODE REVIEW

**Comment by psykzz** [comment]
How does this account for rate limits, which i believe are the current limiting factor?

**Comment by auyer** [comment]
It does not. When the rate limit is reached, this has the same performance as the prior method.
Before reaching the limit, voice states are updated faster.
I should note that this PR is a follow up of #132 and #133

**Comment by denverquane** [comment]
Sorry for my late response, but this code doesn't address the need for tasks to be completed *in priority order*, which we discussed with the previous PR? Dead/Alive players need to me muted/deafened according to the priority ordering, as is the case with the current Master branch (no leaked information between user groups)

**Comment by auyer** [comment]
@denverquane In the last PR I had the priority list removed. In this one, I've kept the priority list and added the "worker" method to dispatch the voice state change command.

**Comment by slang25** [comment]
I've been using this fork for the past week and it has been working great on up to 10 players fyi 👍 

I also adopted 2 bot auth tokens, so that could have caused the improvement I perceived, but I can certainly vouch that this PR is in a good state.

**Pull request closed without merging**
