### PR TITLE
Added more detail for Heroku installation

### PR DESCRIPTION
**Pull request by surdu**
In my case, I also didn't need the `host.txt` thing, but didn't wanted to remove it without knowing what it's for. Any idea if that's needed anymore ?

### CODE REVIEW

**Comment by denverquane** [comment]
I just merged a PR related to Heroku config; that might invalidate some of this PR? Regardless, I appreciate the documentation! And no, the host.txt is not needed anymore

**Comment by surdu** [comment]
Could you please link that PR please. The top most closed PRs I can see related to Heroku are two closed, not merged, and one that just modified what seems to be the version of Go used by the script, which I don't think should affect what parameters are needed for the script on Heroku.

I'm removing the hosts.txt path if it's not needed anymore.

**Comment by denverquane** [comment]
Yeah no sweat, should be here: https://github.com/denverquane/amongusdiscord/pull/136

It's not directly documentation-focused, but figured it might affect any subsequent notes and knowledge :)

**Comment by surdu** [comment]
Tonight we have some gaming to be done, but after this I'll try to re-deploy the bot on Heroku and see if anything changed ;)

**Comment by surdu** [comment]
PS: I have a feeling that the extra vars that are needed can be easily determined/set from code. I'll also look into that and maybe enhance this PR

**Comment by uchihasasuke161** [comment]
After seeing people asking for help with heroku, I feel we should set SERVER_URL to required to make the installations a lot more easier for users. The url will always be ```https://their-app-name.herokuapp.com``` and also set EXT_PORT default value to 443. This way after deployment, they don't have to go the app settings and play around with the config

**Pull request closed without merging**
